#!/usr/bin/env python3

import sys
import os
import platform
import pprint
import argparse
import logging
import subprocess
import json
import shutil
from pathlib import Path

__PROG__ = 'restique'
__VERSION__ = '0.0.1'

pp = pprint.PrettyPrinter(width=80)

def fatal_exit(msg = 'An error occurred'):
    logging.error(msg)
    sys.exit(1)

def get_config_file_path(args):
    if args.config:
        p = Path(args.config).expanduser().resolve()
        if p.is_file():
            return str(p)
        else:
            fatal_exit('No config file located at \'' + args.config + '\'')

    config_paths = [
        './.restiquerc',
        '~/.restiquerc',
        '~/.config/restique/config',
        '/etc/restique.rc',
    ]

    for file_path in config_paths:
        file_path = Path(file_path).expanduser().resolve()
        if file_path.is_file():
            return str(file_path)

    fatal_exit('Couldn\'t find a config file. Valid config file locations are ' + str(config_paths) + ' or specified through the --config argument')

profile_field_types = {
    'json': bool,
    'quiet': bool,
    'no_lock': bool,
    'files': list,
    'excludes': list,
    'keep_tags': list,
    'forget_tags': list,
    'forget_hosts': list,
    'hooks': dict,
    'pre_repo': list,
    'post_repo': list,
}

config_args = {
    'repository': '--repo',
    'json': '--json',
    'quiet': '--quiet',
    'no_lock': '--no-lock',
    'excludes': '--exclude',
    'keep_last': '--keep-last',
    'keep_hourly': '--keep-hourly',
    'keep_daily': '--keep-daily',
    'keep_weekly': '--keep-weekly',
    'keep_monthly': '--keep-monthly',
    'keep_yearly': '--keep-yearly',
    'keep_within': '--keep-within',
    'keep_tags': '--keep-tag',
    'forget_tags': '--tag',
    'forget_hosts': '--host',
}

def merge_profiles(p1, p2):
    merged_profile = {}
    keys = list(set(list(p1.keys()) + list(p2.keys())))

    for key in keys:
        t = profile_field_types[key] if key in profile_field_types else None

        if t == dict:
            p1_value = p1[key] if key in p1 else {}
            p2_value = p2[key] if key in p2 else {}
            merged_profile[key] = merge_profiles(p1_value, p2_value)

        elif t == list:
            p1_value = p1[key] if key in p1 else []
            p2_value = p2[key] if key in p2 else []
            new_value = p1_value + p2_value
            merged_profile[key] = new_value

        else:
            new_value = p1[key] if key in p1 else None;
            if key in p2:
                new_value = p2[key]
            merged_profile[key] = new_value

    return merged_profile

def get_profile_config(config, profile_name):
    default_config = config['global'] if 'global' in config else {}
    profiles = config['profiles'] if 'profiles' in config else {}
    default_profile_name = config['default_profile'] if 'default_profile' in config else None
    restic_path = config['restic_path'] if 'restic_path' in config else None;

    if not profile_name and not default_profile_name:
        fatal_exit('Profile not specified or no \'default_profile\'')

    profile_name = profile_name if profile_name else default_profile_name

    profile_config = merge_profiles({}, default_config)

    for pname in profile_name.split(','):
        if not pname in profiles.keys():
            fatal_exit('Profile \'' + pname + '\' not found')

        logging.debug('Merging profile \'' + pname + '\'')
        profile_config = merge_profiles(profile_config, profiles[pname])

    profile_config['restic_path'] = restic_path

    return profile_config

def check_config(config, required_keys = []):
    minimum_required_keys = [
        'password',
        'repository',
    ]

    all_required_keys = minimum_required_keys + required_keys;

    for key in all_required_keys:
        if not key in config:
            fatal_exit('Missing required config option \'' + key + '\'')

    if config['repository'].startswith('swift:'):
        fatal_exit('OpenStack Swift repositories are currently not supported')

def check_forbidden_args(args, forbidden = []):
    default_forbidden_args = [
        '--password-file',
    ]

    all_forbidden_args = default_forbidden_args + forbidden

    for key in args:
        if key in all_forbidden_args:
            fatal_exit('Argument \'' + key + '\' is currently not supported')

def get_restic_path(config):
    p = config['restic_path'] if 'restic_path' in config and config['restic_path'] != None else 'restic'
    restic_path = shutil.which(p)
    if not restic_path:
        fatal_exit('restic executable path not found')

    logging.debug('Restic path: \'' + restic_path + '\'')
    return restic_path

def get_process(cmd, env = {}):
    env_with_path = env.copy()
    env_with_path.update(os.environ.copy())

    process = subprocess.Popen(
        cmd,
        #stdin=subprocess.PIPE,
        stdout=subprocess.PIPE,
        bufsize=1,
        universal_newlines=True,
        env=env_with_path,
    )

    return process

def run_quiet_command(cmd, env = {}):
    logging.debug('Quiet command: ' + ' '.join(cmd))

    p = subprocess.run(
        cmd,
        env=env,
        capture_output=True,
        shell=False,
    )
    return p.returncode

def run_interactive_command(cmd, env = {}):
    logging.debug('Interactive command: ' + ' '.join(cmd))

    try:
        process = get_process(cmd, env)
        output = process.communicate()[0]

        sys.stdout.write(output)
        sys.stdout.flush()

        rc = process.poll()
        return rc;

    except KeyboardInterrupt:
        logging.info('Received keyboard interrupt')
        return None;

def run_noninteractive_command(cmd, env = {}):
    logging.debug('Non-interactive command: ' + ' '.join(cmd))

    try:
        process = get_process(cmd, env)
        while True:
            output = process.stdout.readline()
            if output == '' and process.poll() is not None:
                break
            if output:
                sys.stdout.write(output)

            sys.stdout.flush()

        rc = process.poll()
        return rc;

    except KeyboardInterrupt:
        logging.info('Received keyboard interrupt')
        return(None)

def run_hook(cmd, env):
    env_with_path = env.copy()
    env_with_path.update(os.environ.copy())

    return subprocess.run(
        cmd,
        env=env_with_path,
        shell=True,
        check=True,
    )


def run_hooks(config, env, hook_name):
    if ('hooks' not in config):
        logging.debug('No hooks to run at all')
        return True

    if (hook_name not in config['hooks']):
        logging.debug('No ' + hook_name + ' hooks to run')
        return True

    hooks = config['hooks'][hook_name]

    successful = True
    for hook_cmd in hooks:
        logging.debug('Running ' + hook_name + ' hook: ' + hook_cmd)
        try:
            rc = run_hook(hook_cmd, env)
        except subprocess.CalledProcessError as err:
            successful = False
            logging.error(err)
            break

    return successful

def run_cmd_hooks(config, env, hook_name):
    if not run_hooks(config, env, hook_name):
        fatal_exit('One or more \'' + hook_name + '\' hooks failed.')

def get_cmd_arg(prop, config):
    arg = config_args[prop]

    if (prop in config):
        if prop in profile_field_types and profile_field_types[prop] == bool:
            if config[prop] == True:
                return [arg]
            else:
                return []

        if prop in profile_field_types and profile_field_types[prop] == list:
            cmd_parts = []

            for value in config[prop]:
                cmd_parts += [
                    arg,
                    value,
                ]
            return cmd_parts
        
        return [
            arg,
            str(config[prop]),
        ]

    return []

def get_base_cmd(command, config):
    cmd = []
    cmd += [get_restic_path(config)]

    cmd += get_cmd_arg('repository', config)
    cmd += get_cmd_arg('quiet', config)
    cmd += get_cmd_arg('json', config)
    cmd += get_cmd_arg('no_lock', config)

    cmd += [command]

    return cmd;

def get_base_env(config):
    env = {
        'RESTIC_PASSWORD': config['password'],
    }

    if config['repository'].startswith('s3:'):
        check_config(config, [
            'aws_access_key',
            'aws_secret_key',
        ])
        env.update({
            'AWS_ACCESS_KEY_ID': config['aws_access_key'],
            'AWS_SECRET_ACCESS_KEY': config['aws_secret_key'],
        })

    if config['repository'].startswith('b2:'):
        check_config(config, [
            'b2_account_id',
            'b2_account_key',
        ])
        env.update({
            'B2_ACCOUNT_ID': config['b2_account_id'],
            'B2_ACCOUNT_KEY': config['b2_account_key'],
        })

    if config['repository'].startswith('azure:'):
        check_config(config, [
            'azure_account_name',
            'azure_account_key',
        ])
        env.update({
            'AZURE_ACCOUNT_NAME': config['azure_account_name'],
            'AZURE_ACCOUNT_KEY': config['azure_account_key'],
        })

    if config['repository'].startswith('gs:'):
        check_config(config, [
            'google_project_id',
            'google_application_credentials',
        ])
        env.update({
            'GOOGLE_PROJECT_ID': config['google_project_id'],
            'GOOGLE_APPLICATION_CREDENTIALS': config['google_application_credentials'],
        })

    return env

def initialize(config, args):
    logging.debug('Checking if repos is initialized')
    env = get_base_env(config)
    cmd = get_base_cmd('snapshots', config)
    rc = run_quiet_command(cmd, env)
    if rc != 0:
        if 'initialize' in config and config['initialize'] == True:
            logging.debug('Repo not yet initialized')
            logging.debug('Initializing repo')
            initCmd = get_base_cmd('init', config)
            initRc = run_noninteractive_command(initCmd, env)

            if initRc != 0:
                sys.exit(rc)
        else:
            logging.debug('Repo not initialized. Exiting')
            sys.exit(1)
    else:
        logging.debug('Repo already initialized')

def cmd_default(command, config, args):
    logging.debug('Running default command handler')

    check_config(config)
    check_forbidden_args(args.resticargs)

    env = get_base_env(config)
    cmd = get_base_cmd(command, config)

    cmd += args.resticargs

    run_cmd_hooks(config, env, 'pre_repo')
    run_cmd_hooks(config, env, 'pre_' + command)
    initialize(config, args)
    rc = run_noninteractive_command(cmd, env)
    run_cmd_hooks(config, env, 'post_' + command)
    run_cmd_hooks(config, env, 'post_repo')
    sys.exit(rc)

def cmd_backup(command, config, args):
    logging.debug('Running backup command handler')

    check_config(config)
    check_forbidden_args(args.resticargs)

    env = get_base_env(config)
    cmd = get_base_cmd(command, config)

    from_stdin = '--stdin' in args.resticargs

    if not from_stdin:
        check_config(config, [
            'files',
        ])

        cmd += config['files']
        cmd += get_cmd_arg('excludes', config)

    cmd += args.resticargs

    run_cmd_hooks(config, env, 'pre_repo')
    run_cmd_hooks(config, env, 'pre_' + command)
    initialize(config, args)
    rc = run_noninteractive_command(cmd, env)
    run_cmd_hooks(config, env, 'post_' + command)
    run_cmd_hooks(config, env, 'post_repo')
    sys.exit(rc)

def cmd_forget(command, config, args):
    logging.debug('Running forget command handler')

    check_config(config)
    check_forbidden_args(args.resticargs)

    env = get_base_env(config)
    cmd = get_base_cmd(command, config)

    cmd += get_cmd_arg('keep_last', config)
    cmd += get_cmd_arg('keep_hourly', config)
    cmd += get_cmd_arg('keep_daily', config)
    cmd += get_cmd_arg('keep_weekly', config)
    cmd += get_cmd_arg('keep_monthly', config)
    cmd += get_cmd_arg('keep_yearly', config)
    cmd += get_cmd_arg('keep_within', config)
    cmd += get_cmd_arg('keep_tags', config)
    cmd += get_cmd_arg('forget_tags', config)
    cmd += get_cmd_arg('forget_hosts', config)

    cmd += args.resticargs

    run_cmd_hooks(config, env, 'pre_repo')
    run_cmd_hooks(config, env, 'pre_' + command)
    initialize(config, args)
    rc = run_noninteractive_command(cmd, env)
    run_cmd_hooks(config, env, 'post_' + command)
    run_cmd_hooks(config, env, 'post_repo')
    sys.exit(rc)

def cmd_key(command, config, args):
    logging.debug('Running key command handler')

    check_config(config)
    check_forbidden_args(args.resticargs)

    env = get_base_env(config)
    cmd = get_base_cmd(command, config)

    cmd += args.resticargs

    rc = None
    run_cmd_hooks(config, env, 'pre_repo')
    run_cmd_hooks(config, env, 'pre_' + command)

    initialize(config, args)
    if args.resticargs and 'add' in args.resticargs:
        rc = run_interactive_command(cmd, env)
    else:
        rc = run_noninteractive_command(cmd, env)

    run_cmd_hooks(config, env, 'post_' + command)
    run_cmd_hooks(config, env, 'post_repo')

    sys.exit(rc)

def cmd_version(command, config, args):
    logging.debug('Running version command handler')

    cmd = get_base_cmd(command, config)

    run_cmd_hooks(config, {}, 'pre_repo')
    run_cmd_hooks(config, {}, 'pre_' + command)
    print(__PROG__ + ' ' + __VERSION__)
    print('python ' + platform.python_version())
    rc = run_noninteractive_command(cmd, {})
    run_cmd_hooks(config, {}, 'post_' + command)
    run_cmd_hooks(config, {}, 'post_repo')

    sys.exit(rc)

def cmd_test(command, config, args):
    check_config(config)
    check_forbidden_args(args.resticargs)

    env = get_base_env(config)
    if not run_hooks(config, env, 'pre_repo'):
        fatal_exit('Hooks failed.')

    env = get_base_env(config)
    cmd = get_base_cmd(command, config)
    run_cmd_hooks(config, env, 'pre_repo')
    run_cmd_hooks(config, env, 'pre_' + command)
    logging.debug(command)
    logging.debug(pp.pformat(config))
    logging.debug(pp.pformat(env))
    logging.debug(pp.pformat(cmd))
    run_cmd_hooks(config, env, 'post_' + command)
    run_cmd_hooks(config, env, 'post_repo')

def main(args, loglevel):
    logging.basicConfig(format='%(levelname)s: %(message)s', level=loglevel)

    config_path = get_config_file_path(args)

    logging.debug('Using config file: ' + config_path);

    try:
        with open(config_path) as config_file:
            config = json.load(config_file)
    except json.decoder.JSONDecodeError as err:
        fatal_exit('Invalid JSON in config file ' + config_path + '\n  ' + str(err));

    profile_config = get_profile_config(config, args.profile)

    commands = {
        'backup': cmd_backup,
        'forget': cmd_forget,
        'key': cmd_key,
        'version': cmd_version,
        'test': cmd_test,
    }

    if args.command in commands:
        commands[args.command](args.command, profile_config, args)
    else:
        cmd_default(args.command, profile_config, args)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        prog=__PROG__,
        description='A wrapper around restic that supports profiles',
    )

    parser.add_argument(
        '-V',
        '--version',
        action='version',
        version='%(prog)s ' + __VERSION__,
    )

    parser.add_argument(
        '-d',
        '--debug',
        action='store_true',
        help='print debug output',
    )

    parser.add_argument(
        '-c',
        '--config',
        metavar='PATH',
        help='path to a config file',
    )

    parser.add_argument(
        '-p',
        '--profile',
        metavar='NAME',
        help='specify which backup profile to use',
    )

    parser.add_argument(
        'command',
        help='restic command to run',
    )

    parser.add_argument(
        'resticargs',
        nargs=argparse.REMAINDER,
        help='arguments passed directly to restic',
    )

    args = parser.parse_args()

    if args.debug:
        loglevel = logging.DEBUG
    else:
        loglevel = logging.INFO

    main(args, loglevel)
